### ISSUE TITLE
Windows Version closes instantly

### ISSUE THREAD

**Issue by Eskalo** [marcoklein/impftermin#37]
The Windows Version closes instantly after the first start without any error message. Chromium does not pop-up, the terminal just closes...

**Comment by marcoklein** [comment]
Hi @Eskalo, could you execute the application through the command line to see the logs? This happens if there is an issue with Chromium and sometimes the download seems to be corrupt or something.

You could also just try deleting the chromium installation by typing `%temp%` into your explorer and deleting the `.local-chromium` folder.

Hope that helps.

**Comment by Eskalo** [comment]
Hi @marcoklein, deleting the chromium installation worked! Thx for fast answer, i will close this issue.
