### ISSUE TITLE
Address changed

### ISSUE THREAD

**Issue by Meng95** [marcoklein/impftermin#48]
Hi, I typed an address at fist. But I have to change it to another address to get the vaccination. But every time I open the application, it always use the previous address and I don't know how to stop and change it. I'm glad if you can give me any suggesstion.

**Comment by quinn-dev** [comment]
Hey @Meng95,

your Impfterminservice address, alongside with other configuration options, is saved in the `config.json` file in the directory in which you are running the application. To change the address, you have two options:

## Option 1: Manually edit your `config.json`

Look for the `url` field in the `queue`:
```json
{
  "intervalInMinutes": 15,
  "queue": [
    {
      "url": "https://002-iz.impfterminservice.de/impftermine/service?plz=XXXXX"
    }
  ]
}
```

...and replace the URL with your new URL.

## Option 2: Remove the `config.json` and re-run the application

Since it won't find a pre-existing configuration, it will take you through the configuration wizard again and ask you for your Impfterminservice URL.
